/* keep scripts disabled to avoid jQuery dependency */

module.exports = {
  preBootstrapCustomizations: './src/theme/variables.scss',
  mainSass: './src/theme/main.scss',
  verbose: false,
  debug: false,
  scripts: {
    transition: false,
    alert: false,
    button: false,
    carousel: false,
    collapse: false,
    dropdown: false,
    modal: false,
    tooltip: false,
    popover: false,
    scrollspy: false,
    tab: false,
    affix: false
  },
  styles: {
    mixins: true,
    normalize: true,
    print: true,
    glyphicons: false,
    scaffolding: true,
    type: true,
    code: false,
    grid: true,
    tables: false,
    forms: true,
    buttons: true,
    'component-animations': false,
    dropdowns: false,
    'button-groups': true,
    'input-groups': true,
    navs: true,
    navbar: true,
    breadcrumbs: false,
    pagination: false,
    pager: false,
    labels: true,
    badges: false,
    jumbotron: true,
    thumbnails: false,
    alerts: false,
    'progress-bars': false,
    media: false,
    'list-group': true,
    panels: true,
    wells: false,
    'responsive-embed': false,
    close: false,
    modals: false,
    tooltip: false,
    popovers: true,
    carousel: false,
    utilities: true,
    'responsive-utilities': true
  }
};
